# Development stage
FROM node:16 as development

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# For development (with hot-reload)
CMD ["npm", "run", "serve"]

# Production build
FROM development as builder
RUN npm run build

# Production stage
FROM nginx:stable-alpine as production
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]