version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - VUE_APP_API_URL=http://backend:3001

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '3001:3001'
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
